### ISSUE TITLE
List candidates of data sources / journals

### ISSUE THREAD

**Issue by daniel-jettka** [DH-RSE/software-citation#1]

**Comment by daniel-jettka** [comment]
* DH Quarterly 
   * available for download: http://digitalhumanities.org/dhq/data/dhq-xml.zip
* Directory of OA journals
  * https://doaj.org/
* DH conference
  * https://github.com/orgs/ADHO/repositories

**Comment by anneferger** [comment]
* Digital Humanities Research
  * https://www.transcript-verlag.de/biup/bielefeld-university-press/digital-humanities-research/?f=12320

**Comment by daniel-jettka** [comment]
> * Digital Humanities Research
>       
>       * https://www.transcript-verlag.de/biup/bielefeld-university-press/digital-humanities-research/?f=12320

Oh cool, magst Du mal schauen, ob und wieviel man da so kriegen könnte? Das sind Open Access Monographien/Sammelbände, oder? Wäre evtl. auch eine interessante Datenquelle.

**Comment by anneferger** [comment]
Und gerade auch noch (bei Twitter) gefunden: https://dh-abstracts.library.cmu.edu/ - Filtermöglichkeit: Volltext öffentlich verfügbar und Englisch

**Comment by anneferger** [comment]
https://dh-abstracts.library.cmu.edu/downloads csv download available with fulltext partly available
