### ISSUE TITLE
Evaluate annotation tools

### ISSUE THREAD

**Issue by daniel-jettka** [DH-RSE/software-citation#2]
* ideally directly suitable for annotation of TEI documents

**Comment by daniel-jettka** [comment]
- https://brat.nlplab.org/ (use with current annotation model of Krüger et al.)
- https://webanno.github.io/webanno/
- https://inception-project.github.io/

**Comment by hennyu** [comment]
- CATMA: https://catma.de/

**Comment by hennyu** [comment]
* Ediarum: https://www.bbaw.de/en/bbaw-digital/telota/research-and-software/ediarum

**Comment by daniel-jettka** [comment]
Inception (fka Webanno):

- Import von TEI möglich (Textinhalt unterhalb <body>)
- Export nur von anderem TEI möglich und Annotationen sind nur enthalten, wenn vorangelegte Kategorien verwendet werden

![image](https://user-images.githubusercontent.com/18614293/161339967-e891b2ea-a1e8-42d0-8bb3-9319412a7f7b.png)

**Comment by daniel-jettka** [comment]
### Annotonia

- found in ADHO abstracts: 2017/tei/488.tei.xml; "Annotonia: Annotations from Browser to TEI"
- https://github.com/Willa-Cather-Archive/annotonia
- https://digitalcommons.unl.edu/librarydisc/2/

**Comment by anneferger** [comment]
We are using ToolXTractor for pre-annotation and Oxygen for annotation
