### ISSUE TITLE
List other relevant projects, repositories, resources

### ISSUE THREAD

**Issue by anneferger** [DH-RSE/software-citation#3]
* SoMeSci: Software Mentions in Scientific Articles 
    * https://github.com/dave-s477/SoMeSci 
    * https://data.gesis.org/somesci/ 
    * https://github.com/dave-s477/SoMeSci_Code
* Softcite software mention recognition service https://github.com/ourresearch/software-mentions
* ToolXtractor: Extract tools from TEI-encoded abstracts against a matching list 
    * https://github.com/lehkost/ToolXtractor (they used DHQuarterly and ADHO DH tei conference abstracts as their dataset)
    * https://weltliteratur.net/dh-tools-used-in-research/
* SIG-DLS Tool Inventory https://dls.hypotheses.org/774

**Comment by sdruskat** [comment]
I'm active in this field, partly working on the evaluation on a software mentions corpus from COVID papers, partly building an interdisciplinary dataset for my PhD work. Happy to share work as it is realized.
