### ISSUE TITLE
Test annotation workflow

### ISSUE THREAD

**Issue by anneferger** [DH-RSE/software-citation#6]
- [x] create brat Docker image: see https://github.com/anneferger/brat-docker#in-progress-running-the-docker-image
- [x] ADHO xml to tei using TEIGarage: done in 96289114d79d7ae115dbe9ed11a85b74105a1a57, used utilities/tei2txt.sh, TEI creation of the ADHO abstracts was done using DHConvalidator, which also uses TEIGarage/OxGarage functionality
- [x] test SoMeCI conf on ADHO - added in correct place 2ca60e3378fca0edee31dc76373b9d61c0de96e5
- [x] use `git config core.fileMode false` when working with brat (needs to be done in each local repository)

**Comment by daniel-jettka** [comment]
SoMeSci conf: https://github.com/dave-s477/SoMeSci/tree/9f17a43f342be026f97f03749457d4abb1b01dbf/conf

**Comment by anneferger** [comment]
Installing brat using the docker image:
`docker run --name=brat -d -p 8001:80 -v /media/software-citation/data:/bratdata -e BRAT_USERNAME=brat -e BRAT_PASSWORD=brat -e BRAT_EMAIL=brat@example.com anneferger/brat`
