### ISSUE TITLE
customize ODD

### ISSUE THREAD

**Issue by hennyu** [DH-RSE/software-citation#9]
to dos:
- add software annotation specific details to ODD (list of values for key-attribute and ana-attribute)
- automate that with scripts which use the taxonomy and software list as a basis

**Comment by anneferger** [comment]
* Added available ana annotations to odd
* added stylesheet to generate odd with items from Softwarelist
* To do: this XSLT call needs to be added to the GitHub Action so the odd is regenerated when the softwarelist is updated

**Comment by anneferger** [comment]
Done, XSLT call ist added to GitHub Action, for reference: encountered very specific saxon bug: https://saxonica.plan.io/boards/3/topics/8478?r=8480
